### ISSUE TITLE
Adds image code to aria-label on linked images

### ISSUE THREAD

**Issue by amberhinds** [equalizedigital/accessibility-new-window-warnings#4]
I saw this on the Minerva site. It's a really bad bug.

If a linked image is set to open in a new window the link gets an aria-label that contains HTML code.

`<a href="https://www.tableau.com/" target="_blank" rel="noopener" aria-label="<img width=&quot;320&quot; height=&quot;145&quot; decoding=&quot;async&quot; src=&quot;https://minervadev.wpengine.com/wp-content/uploads/2022/12/32.png&quot; alt=&quot;tableau foundation logo&quot;/> , opens a new window"><img width="320" height="145" decoding="async" src="https://minervadev.wpengine.com/wp-content/uploads/2022/12/32.png" alt="tableau foundation logo" class="perfmatters-lazy entered pmloaded" data-src="https://minervadev.wpengine.com/wp-content/uploads/2022/12/32.png" data-ll-status="loaded"><noscript><img width="320" height="145" decoding="async" src="https://minervadev.wpengine.com/wp-content/uploads/2022/12/32.png" alt="tableau foundation logo"/></noscript> <i class="anww-external-link-icon" aria-hidden="true"></i></a>`

**Comment by SteveJonesDev** [comment]
@amberhinds, should an aria-label be added at all in this instance or should it just say "opens a new window"?

**Comment by amberhinds** [comment]
It needs to read the alt text on the image and then opens a new tab. This could be done with screen reader text added in the `<a>` after the` <img>` or it could be done by getting just the alt of the image and adding that to the aria-label.  I think that fix would be more in line with what you're currently doing.

**Comment by SteveJonesDev** [comment]
Updated to account for images. Also, updated to account for existing aria-label on links. Version 1.0.1 on WordPress plugin repo.

https://github.com/equalizedigital/accessibility-new-window-warnings/commit/96334ff029457502264babf4952a3c0ea681412a
